### ISSUE TITLE
Cifar-10 performance 

### ISSUE THREAD

**Issue by theblackcat102** [XifengGuo/CapsNet-Keras#10]
Hi Xi Feng,

May I ask whether you had tried training capsule on cifar-10 or cifar-100 datasets?

My attempt to replicate the paper on cifar-10 accuracy only achieve a 0.54 accuracy. I have set both convolution kernel size to 24, primary capsule size to 64. However, the model stops improving after epoch 14 on cifar-10 datasets. Cifar-100 perform even worse than it's smaller counterpart. 
I wonder if there are any parameters I had missed? 

![figure_1](https://user-images.githubusercontent.com/13172147/32475535-333d22ae-c3ad-11e7-9e5a-ae51dff9eda9.png)

**Comment by XifengGuo** [comment]
@DBlackKat I have not tried on cifar. But someone had done and showed me the result. 
![acc_on_cifar10](https://user-images.githubusercontent.com/20176064/32475921-41efe2a8-c3af-11e7-890e-a5a027293525.jpg)
The model structure is same as the CapsNet on MNIST except the input and output channels changed from 1 to 3. The lam_recon parameter is set to 0.0005 which is not right. It should be set around 0.1. But still the validation loss is decreasing. The final validation accuracy is about 70%, but still highly under-fitting.

I will try this later when I'm available, and come back with new results.

**Comment by tycheyoung** [comment]
@XifengGuo 
lam_recon parameter around 0.1 means 0.0005*(decoder output size), right?
I got highly under-fitted results too :/

**Comment by XifengGuo** [comment]
@tycheyoung Yes. For Cifar10, I assume `lam_recon=0.0005*32*32*3=1.563` is equivalent to the setting of paper. It may take `epochs>100` to converge.

**Comment by sulaimanvesal** [comment]
I tried with two class classification, for cat and dog dataset, with the same lam_recon= 0.36 and here is my output:

`val_loss: 0.1611 - val_capsnet_loss: 0.1445 - val_decoder_loss: 0.0423 - val_capsnet_acc: 0.7686`

This is the result after only 76 epochs and no change until 500 epochs, means no more convergence. I was expecting the model performs better than this as the dataset is around 25000 images. I am wondering how we can increase the depth of the model. Is the number of routing is a matter of adding some new convolution layers?

**Comment by XifengGuo** [comment]
@sulaimanvesal Firstly, you can set the lr decay factor from 0.9 to a larger value, say 0.95, if you are using the learning rate decay. E.g. `lr_decay = callbacks.LearningRateScheduler(schedule=lambda epoch: args.lr * (0.95 ** epoch))`.   

To increase the depth, I assume you can add conventional Conv2D layers before PrimaryCapsule layer. Stacking more Capsule layers, which is a promising research direction, maybe works too, but I haven't tested this.

**Comment by sulaimanvesal** [comment]
@XifengGuo Thank you for your response, I would certainly investigate the stacking of capsule layers. Here, I would like to share the output the model which I trained on Cifer10 based on your implementation with slight changes.

| ![Cifer102.png](https://github.com/sulaimanvesal/CapsNet/blob/master/images/Cifer102.png) | 
|:--:|
| *Validation CapsNet and Validation loss for Cifer10 Dataset|

**Comment by XifengGuo** [comment]
@sulaimanvesal Good work. You can try the settings introduced in the paper. I believe there's much space for the performance to improve. Looking forward to your new results.
![image](https://user-images.githubusercontent.com/20176064/33485835-d88b51ca-d6e2-11e7-84e5-bff725355177.png)

**Comment by JaminFong** [comment]
@XifengGuo Hi Xifeng! I have tried to reproduce your model. It's a good job! But when applied to the Cifar-10 dataset, the result is bad. The test accuracy is only 72.79%(89.40% in the paper).
May I ask you a question about your code, please?
`model.compile(optimizer=optimizers.Adam(lr=args.lr),
                  loss=[margin_loss, 'mse'],
                  loss_weights=[1., args.lam_recon],
                  metrics={'capsnet': 'accuracy'})`
The loss seems to be the margin loss only. But for the lam_recon, I think it is used for the reconstruction loss which should be scaled down. I didn't figure out this part.

**Comment by XifengGuo** [comment]
@JaminFong Yes, I noticed the bad performance on cifar10 too, but I haven't figured out the reason. Other implementations (Pytorch, Tensorflow) cannot get better results either. 

The `total loss = [margin_loss, mse] * [1., args.lam_recon] = margin_loss + args.lam_recon * mse`.

**Comment by sulaimanvesal** [comment]
@XifengGuo I just ran another model with taking into consideration the points which were highlighted in the paper for Cifer10 but with no any significant improvement. ``` Validation loss = 0.26 and Validation CapsNet Loss = 0.225 , Validation Accuracy = 0.698 ```

| ![Cifer2.png](https://github.com/sulaimanvesal/CapsNet/blob/master/images/Cifer2.png) | 
|:--:|

**Comment by JaminFong** [comment]
@XifengGuo Thank you! But I still don't know where 'mse' is calculated out.
Furthermore, I don't know what else can be done except changing lam_recon. As mentioned in the paper, the architecture should be as same as the model used on MNIST. And how to adjust lam_recon remains a question.

**Comment by XifengGuo** [comment]
@JaminFong The model has two outputs: out_caps and out_recon. The losses [margin_loss, mse] are applied on out_caps and out_recon respectively. This is taken care of by Keras.

lam_recon should be set to 0.0005*24*24*3 if you are using cropped images as input.

**Comment by XifengGuo** [comment]
@sulaimanvesal Yeah, it's quite strange. I wonder if something is missing in the paper.

**Comment by JaminFong** [comment]
@XifengGuo Thanks a lot! I got it as for the loss processing, while I'm not so familiar with the usage of Keras.
And I don't quite understand what the real meaning is mentioned in the paper about an ensemble of 7 models and 24*24 patches of the image. I just set the convolution kernel size to 24*24 and use the original input size 32*32.  The test accuracy is only 72.79%.

**Comment by sulaimanvesal** [comment]
@JaminFong Basically, ensemble means building multiple models (typically of differing types) and simple statistics (like calculating the mean) are used to combine predictions.  While, in the paper, they trained an ensemble of 7 same models with 3 routing iterations everytime (each model has different weights and give different accuracy).  They extracted smaller patches of 24x24 form the image to increase the number of the training set.

**Comment by JaminFong** [comment]
@sulaimanvesal Thanks for your reply. However, in my opinion, I don't know whether the performance will benefit from an ensemble of 7 same models, while each model is trained on the same data set. And I think this method may be a little wasting. Do the random patches cause different weights of each model?

**Comment by sulaimanvesal** [comment]
@JaminFong I may say yes, but I am not quite sure. Still, there is some portion of the papers which is not really clear. What I understood, there is something missing in the paper that we do not know about it. Although @XifengGuo implemented almost similar to the paper.

**Comment by raaju-shiv** [comment]
@sulaimanvesal are you planning to make available the model trained on CIFAR-10 on your repository? At the moment, I couldn't find one. Thanks for your understanding.

**Comment by sophchoe** [comment]
@sulaimanvesal Could you share your capsnet.py? I modified 28 to 32 and loaded cifar10 instead of MNIST and get ValueError: All input arrays (x) should have the same number of samples. Got array shapes: [(30000, 32, 32, 1), (10000, 10)]

**Comment by SamitHuang** [comment]
The author has released the code in https://github.com/Sarasra/models/tree/master/research/capsules
Have you guys checked out the missing part in the paper that leads to previous bad results on CIFAR-10 dataset?  @XifengGuo @sulaimanvesal

**Comment by johndpope** [comment]
fyi - this code supposedly uses ensembling techniques with capsnet https://github.com/theidentity/Ensembling_Techniques

**Comment by SuperShinyEyes** [comment]
Has anyone managed to get a decent reconstruction for cifar10? I guess ensemble may result better reconstruction?

**Comment by SuperShinyEyes** [comment]
Here is my result for cifar-10.
I wonder why it's reaching the 90% accuracy which authors claimed.. 🤔
<img width="459" alt="Screenshot 2019-05-17 at 9 44 42" src="https://user-images.githubusercontent.com/5738363/57908331-6b254200-7888-11e9-8234-b2b6b07f5a90.png">

**Comment by ashok-arjun** [comment]
If someone is seeing this thread, a deeper version of capsule networks came out in CVPR 2019 - an implementation is here - https://github.com/brjathu/deepcaps
