### ISSUE TITLE
Type Error Theano

### ISSUE THREAD

**Issue by AliS567** [XifengGuo/CapsNet-Keras#108]
> TypeError: size must be a tuple of int or a Theano Variable with 1 dimension, got [10, 1152, 16, 8] of type <class 'list'>

I am getting the above error when trying to run the code? Is this maybe a Theano version problem? My environment is running Theano 1.0.3

**Comment by XifengGuo** [comment]
@AliS567 
Sorry, I did not and will not test on Theano backend since it is kind of outdated.
I recommend you switch to tensorflow backend.
