### ISSUE TITLE
A TypeError occurred while running this code in Colab

### ISSUE THREAD

**Issue by Bear-Lx** [XifengGuo/CapsNet-Keras#120]
When I was running code in Google Colab, I encountered the following error message:
`File "capsulenet.py", line 244, in <module>routings=args.routings)`
` File "capsulenet.py", line 50, in CapsNet
    name='digitcaps')(primarycaps)`
`File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)`
 ` File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable`
 ` File "/content/drive/My Drive/CapsNet_Keras_master/capsulelayers.py", line 116, in build
    name='W')`
`  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 577, in add_weight
    caching_device=caching_device)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 743, in _add_variable_with_custom_getter
    **kwargs_for_getter)`
 ` File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 141, in make_variable
    shape=variable_shape if variable_shape else None)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 220, in _variable_v1_call
    shape=shape)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 198, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 2598, in default_variable_creator
    shape=shape)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 1434, in __init__
    distribute_strategy=distribute_strategy)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 1567, in _init_from_args
    initial_value() if init_from_fn else initial_value,`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 121, in <lambda>
    init_val = lambda: initializer(shape, dtype=dtype)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops_v2.py", line 542, in __call__
    fan_in, fan_out = _compute_fans(scale_shape)`
  `File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/init_ops_v2.py", line 1015, in _compute_fans
    receptive_field_size *= dim`
`TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'`
I'm sure that tensorflow version is 2.2.0, Does anyone have the same problem?

**Comment by zhangxin9988** [comment]
same error

**Comment by SamiQV** [comment]
Stuck on the same issue, kindly throw some light on it and share how resolve it. @Bear-Lx @zhangxin9988  @kmader @iretiayo 

I am trying to convert the trained model file to a TFLite version where the process throws similar error shown in attached image below. If you need any further details pls let me know.
![Error](https://user-images.githubusercontent.com/100053217/176972828-88b13dcd-1ea0-4517-be57-fdfba3295e1f.jpg)
