### ISSUE TITLE
Dimension Ordering

### ISSUE THREAD

**Issue by jack-kelly** [XifengGuo/CapsNet-Keras#13]
This one is a quick fix, but the code assumes that you are using `"channels-last"`, but I have my defaults set otherwise and it causes an error. You might want to make it explicit with:

```python
K.set_image_data_format('channels_last')
```

**Comment by XifengGuo** [comment]
[jack-kelly](https://github.com/jack-kelly) Thanks, it helps. I’ll revise it at the next commit.
