### ISSUE TITLE
Question on Paper Model Setup

### ISSUE THREAD

**Issue by pGit1** [XifengGuo/CapsNet-Keras#17]
Having an EXTREMELY hard time following the below. 

What does convolutionial "Unit" mean? Where does the 32x6x6 dimension come from? I get the 32 but the 6? Where does the dimension 20x25 come from? Same goes for the 16x10 digit caps dimension...

Are these numbers arbitrarily chosen or derived from opertations happening in the net. Please provide detailed response where possible. I find reading this paper **extremely** frustrating. Hopefully reading this code will be better.

EDIT: I think I answered some of my own questions by looking at your model diagram but would still love your opinion to make sure I am tracking correctly. 

![image](https://user-images.githubusercontent.com/13975114/32856630-5359b9aa-ca13-11e7-9d8f-811320de5c4a.png)

**Comment by XifengGuo** [comment]
[@pGit1](https://github.com/pGit1), I believe the following blogs can help you understand how it works.

https://kndrck.co/posts/capsule_networks_explained/

https://medium.com/@pechyonkin/understanding-hintons-capsule-networks-part-i-intuition-b4b559d1159b

**Comment by pGit1** [comment]
Hi @XifengGuo thanks for reply. I like your code better honestly than those blogs (ive read both a couple of times). I understood a lot more. If I could revise my question after reading your code it would be to explain the CapsuleLayer class. This part is still very fuzzy even after reading code and blogs. Any insight could provide would help. Specifically on "routing" and "inverse transorfamtion" matrix. Not sure how Digit caps layer handles that.
