### ISSUE TITLE
Squash Function Valididty

### ISSUE THREAD

**Issue by pGit1** [XifengGuo/CapsNet-Keras#18]
`
def squash(vectors, axis=-1):
    """
    The non-linear activation used in Capsule. It drives the length of a large vector to near 1 and small vector to 0
    :param vectors: some vectors to be squashed, N-dim tensor
    :param axis: the axis to squash
    :return: a Tensor with same shape as input vectors
    """
    s_squared_norm = K.sum(K.square(vectors), axis, keepdims=True)
    scale = s_squared_norm / (1 + s_squared_norm) / K.sqrt(s_squared_norm + K.epsilon())
return scale * vectors

Shouldnt scale be equal = [s_squared_norm / (1 + s_squared_norm)]*[vectors/ K.sqrt(s_squared_norm + K.epsilon())] per the paper?

![image](https://user-images.githubusercontent.com/13975114/32860171-cc6f5dc6-ca1e-11e7-95a5-c6992c0d1bd0.png)

**Comment by LawnboyMax** [comment]
**s<sub>j</sub>** (or `vectors` in the code) is the total input of capsule **j**. **v<sub>j</sub>** is vector output of capsule **j**. The squashing function scales the input **s<sub>j</sub>**, by multiplying **s<sub>j</sub>** by the rest of the formula which can be thought of as a scaling factor. Therefore `return scale * vectors` is the scaled(squashed) input vector, which is the output vector.

What you have written is a formula for output vector calculated in one step.

**Comment by XifengGuo** [comment]
[pGit1](https://github.com/pGit1) Thanks. I believe [LawnboyMax](https://github.com/LawnboyMax) has given a very clear explanation. Thanks too [LawnboyMax](https://github.com/LawnboyMax).

**Comment by pGit1** [comment]
@LawnboyMax 

THANK YOU!

Duh... I'm stuuuupid.....cannot believe i missed that. Too confused with all this "routing" and "inverse graphics" stuff and started missing easy stuff :(. I have absolutely no idea what the Capsule layer is doing which lead to frustration which leads to simple mental errors. :( Good lesson. Tension and frustration dont help anything. Just leads to preventable errors. 

Thanks again.
