### ISSUE TITLE
tf.map_fn instead of tf.scan

### ISSUE THREAD

**Issue by chrislybaer** [XifengGuo/CapsNet-Keras#19]
You should really use tf.map_fn instead of tf.scan, in your code the first argument (the accumulator) of the tf.scan function is not even used. Therefore, using tf.map_fn should do the same just faster because it does not have to account for dependencies between the evaluations of the lambda function on the elements that are to be processed.

**Comment by XifengGuo** [comment]
@chrislybaer Thanks. Fixed!
