### ISSUE TITLE
Get the batch size

### ISSUE THREAD

**Issue by chrislybaer** [XifengGuo/CapsNet-Keras#20]
Hi,

I just saw that somewhere in your capsulelayers.py code you wrote a comment:
`# b=K.zeros(shape=[batch_size, num_capsule, input_num_capsule]). I just can't get batch_size
`
In tensorflow you could get it using tf.shape(inputs)[0]. Apparently, there is a difference between inputs.shape and tf.shape(inputs). You can also use this to compute the inputs_hat more efficiently by tiling.W and then using a regular matmul instead of the tf.map_fn.

Best,
Chris

**Comment by XifengGuo** [comment]
@chrislybaer Thanks, that's a big help. I have fixed `b` by using `tf.shape(inputs)[0]`.
But tiling W will take much more computational time (using tile 180s vs using tf.map_fn 110s on a single GTX 1070 GPU).

**Comment by chrislybaer** [comment]
On my GTX 960 tiling is much faster than map_fn. Good to know tough, thank you!

**Comment by XifengGuo** [comment]
@chrislybaer Really? Could you report the time of this code with tf.tile? I am curious about the difference. Thanks.

**Comment by chrislybaer** [comment]
I can run an experiment tomorrow. I just made this experience in my tensorflow implementation (where apparently something is wrong with the routing :().
