### ISSUE TITLE
Problem in running for systems not having GPU. Please help.

### ISSUE THREAD

**Issue by sjsingh91** [XifengGuo/CapsNet-Keras#21]
> C:\Users\jeet\Documents\GitHub\CapsNet-Keras>python capsulenet.py --num_routing 1
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 62, in preload_check
>     ctypes.WinDLL(build_info.nvcuda_dll_name)
>   File "C:\Users\jeet\Anaconda3\lib\ctypes\__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "capsulenet.py", line 20, in <module>
>     from keras import layers, models, optimizers
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
>     from . import utils
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
>     from . import conv_utils
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 3, in <module>
>     from .. import backend as K
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 83, in <module>
>     from .tensorflow_backend import *
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
>     import tensorflow as tf
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
>     self_check.preload_check()
>   File "C:\Users\jeet\Anaconda3\lib\site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
>     % build_info.nvcuda_dll_name)
> ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

**Comment by XifengGuo** [comment]
@sjsingh91 I have not tested in Windows. But I think the error is caused by the incorrect configuration of Tensorflow. Did you install tensorflow by `conda install tensorflow` or `pip install tensorflow`? The traceback says *Could not find 'nvcuda.dll'* which means you installed an GPU-enabled Tensorflow while you didn't configure CUDA.
Please check it again according to instructions in https://github.com/tensorflow/tensorflow

**Comment by bibinjose** [comment]
I have the program in windows 10 with TensorFlow with CPU support only.It works.
