### ISSUE TITLE
Can we run this on Theano?

### ISSUE THREAD

**Issue by vivek14632** [XifengGuo/CapsNet-Keras#22]
Hi Xi,

I want to run the code on Theano. Can you suggest any other implementation of CapsNet which is over Theano?.

Thanks.

**Comment by XifengGuo** [comment]
@vivek14632 I believe this repo can be easily adapted to Theano backend by taking care of the order of data channels and some tf functions.
There maybe other implementation by Theano, which you can search on GitHub.

**Comment by vivek14632** [comment]
Thanks @XifengGuo
