### ISSUE TITLE
Test accuracy 0

### ISSUE THREAD

**Issue by dceregatti** [XifengGuo/CapsNet-Keras#23]
Hi, I wonder why I'm getting accuracy 0 on test. I did not change the code...I trained from scratch and then loaded the trained_model.h5 file as told to do.

**Comment by XifengGuo** [comment]
@d-gatti That’s odd. Can you try again? Or you can download the pretrained weights from the provided link.

**Comment by dceregatti** [comment]
I did try twice on full training and once using the best weights from one of the previous trainings. The link redirects to a Chinese website, was not able to figure out how to download it, sorry. Thanks for the reply!

**Comment by XifengGuo** [comment]
@dceregatti There’s no enough information for me to figure out the reason. Can you run the code on another computer?

**Comment by dceregatti** [comment]
I download the trained model from your link, which is trained_model-11-19.h5 and now I get this error:
ValueError: Layer #2 (named "digitcaps" in the current model) was found to correspond to layer digitcaps in the save file. However the new layer digitcaps expects 2 weights, but the saved weights have 1 elements.

I am trying to run the test as below:
$ python capsulenet.py --is_training 0 --weights result/trained_model-11-19.h5

Am I missing any package or something?

**Comment by dceregatti** [comment]
Update: needed to set the test acc as float when printing it. I actually reached 99.65% test accuracy. Thanks!!!

**Comment by XifengGuo** [comment]
@dceregatti Thanks for the feedback.
