### ISSUE TITLE
How to apply the network for many classes

### ISSUE THREAD

**Issue by strongrex2001** [XifengGuo/CapsNet-Keras#24]
In mnist, it is 10 classes, and we need 10 capsules; but if the num_capsule continue to go up OOM will happen...
So how to apply the CapsNet for .., for example, 50 classes or even more?
Thank you for answering!

**Comment by XifengGuo** [comment]
@strongrex2001 There’s no good solution in current version. Maybe using more Conv2D layers is a possible way.
