### ISSUE TITLE
dim_capsule 8 != 16 in the code

### ISSUE THREAD

**Issue by strongrex2001** [XifengGuo/CapsNet-Keras#29]
In [capsulenet.py line 43](https://github.com/XifengGuo/CapsNet-Keras/blob/7135b2fc7dbd476b18cd54a0d87671c72ba42796/capsulenet.py#L43)
The primarycap's dim_capsule is 8.
But the CapsuleLayer's dim_capsule is 16.
Though it doesn't seem to be a problem when training, I wonder why it is unequal...

**Comment by XifengGuo** [comment]
@strongrex2001 capsules in different layers have different dimensions. You can get it in the paper.

**Comment by Pizzafarmer** [comment]
https://www.youtube.com/watch?v=2Kawrd5szHE

**Comment by strongrex2001** [comment]
Thank you! I had been confused by the "Reshape"..
