### ISSUE TITLE
Valid padding in CapNets

### ISSUE THREAD

**Issue by phongnhhn92** [XifengGuo/CapsNet-Keras#32]
Hello sir,
I am following the Capsule Network paper and your implementation.
I have a quick question about the valid padding in the conv2 you used to get output for the Primary Caps. So as I understand, after the 1st conv layer, the size of output is (batchsize,20,20,256). So if the conv2 has 256, 9x9 kernel, stride 2 then the formula output should be (20-9+2*p)/2+1 = 6. However, mathematically, the formula above can not be solved so I would like to ask how did exactly padding (valid) works in this situation to have the output is (batchsize,6,6,256).
Thanks !

**Comment by XifengGuo** [comment]
@phongnhhn92 Valid padding means `p=0`. The actual formula is `floor((20-9+2*0)/2)+1=6`.

**Comment by phongnhhn92** [comment]
Thanks !
