### ISSUE TITLE
Error in multigpu

### ISSUE THREAD

**Issue by danijel3** [XifengGuo/CapsNet-Keras#33]
There is a small bug in [capsulenet-multi-gpu.py:129](https://github.com/XifengGuo/CapsNet-Keras/blob/92756e02bc1209e84750792055580fa1a9499cb3/capsulenet-multi-gpu.py#L129)

The function returns 3 values, but is assigned to 2. The line should be rewritten, at least, to this:

`model, eval_model, _ = CapsNet(input_shape=x_train.shape[1:],`

**Comment by XifengGuo** [comment]
@danijel3 Thanks, you’re right.
