### ISSUE TITLE
Utils and plots

### ISSUE THREAD

**Issue by danijel3** [XifengGuo/CapsNet-Keras#36]
Matplotlib causes a lot of issues when run on remote servers without X. If not addressed, the program crashes when it tries to save the plots. I managed to resolve this by adding the following line to the start of utils.py (after the imports):

`plt.switch_backend('agg')`

I tried some other solutions, but this one seems to do the trick (even though I still get a bunch of warnings). Now, I'm aware that this isn't something you would be willing to add to master for sure, but it may be worthwhile to at least mention it in the Readme, or something...

**Comment by XifengGuo** [comment]
@danijel3 I think it’s better to remove the code of plotting when running on servers, and just save the log and model instead. Dealing with figures in local computer is a better way.

**Comment by danijel3** [comment]
Ok, so I understand that I can comment out lines [70-71](https://github.com/XifengGuo/CapsNet-Keras/blob/6e616da6eb5e4a88a571f228cc4e1ffab118dff2/capsulenet-multi-gpu.py#L70) in capsulenet-multi-gpu.py and after training simply run `python utils.py` with the log dir on a GUI machine?

**Comment by XifengGuo** [comment]
@danijel3 exactly
