### ISSUE TITLE
Keyword argument not understood

### ISSUE THREAD

**Issue by raaju-shiv** [XifengGuo/CapsNet-Keras#37]
I'm working with Anaconda 4.3.2 and Keras 2.0.9
When I try to run capsnet.py or its multi-gpus version, on my own data, i am stuck with the following error:
**TypeError: ('Keyword argument not understood:', 'routings')**
When i searched online for the error, i found from a post  that the TypeError occurs when 'kwargs' doesn't contain the type (routings) and/or serialization would have happened in a different Anaconda distribution and using the same Anaconda distribution fixes the error. 
need your help on this.

**Comment by XifengGuo** [comment]
@raaju-shiv Thanks for the feedback. I have fixed this in the newest commit.
