### ISSUE TITLE
ImportError: No module named 'PIL'

### ISSUE THREAD

**Issue by wfreshet** [XifengGuo/CapsNet-Keras#49]
run the script 'capsulenet-multi-gpu.py'
a error occurs.
from PIL import Image
ImportError: No module named 'PIL'

How can i add the PIL file?
Thanks for your attention!

**Comment by rezazad68** [comment]
You need to install PIL. simply run pip install pil on your console

**Comment by wuzy361** [comment]
when i run "pip list"  ,it shows that "pillow (4.3.0)" has existed,
but when i run 
bigdata@bd-pc:~/桌面/CapsNet-Keras-master$ python capsulenet.py -h
Using TensorFlow backend.
Traceback (most recent call last):
  File "capsulenet.py", line 25, in <module>
    from PIL import Image
ImportError: No module named PIL

**Comment by Borda** [comment]
check the version of your `python` and `pip` association
```
python --version
pip --version
```
both should point to `python2.x` or `python3.x`

**Comment by damienstanton** [comment]
@wfreshet if you're using Python 3, you should be using a virtual environment, either through the built-in `venv` module or by using Anaconda/Miniconda, or similar to avoid this type of issue. I prefer just using Python 3's faculties.

You can activate a new virtual environment like this:
```sh
python3 -m venv env
source env/bin/activate
```
You'll know you are in the venv by (env) showing near your terminal prompt. Now you are safe to ensure that any modules you need are installed for this environment.

Exit the venv by:
```sh
deactivate
```
