### ISSUE TITLE
Appropriate credit for authors

### ISSUE THREAD

**Issue by cbrew** [XifengGuo/CapsNet-Keras#5]
The authors of the paper are:

Sara Sabour, Nicholas Frosst, Geoffrey Hinton

In Hinton's talks about this he is always careful to make clear that while he may have thought of the idea, it was his co-authors who made it work. So I think the README should say Sabour's Capsule Network.

**Comment by XifengGuo** [comment]
@cbrew Yeah, thanks. I will modify the README right away.

**Comment by XifengGuo** [comment]
Since the issue has been solved, I'll close it now. If you find more problems, feel free to reopen it. @cbrew
