### ISSUE TITLE
train et validation data

### ISSUE THREAD

**Issue by Pelups** [XifengGuo/CapsNet-Keras#51]
Hey !
Thank you for your job and sharing it !

I have a question regarding the train data returned by "train_generator" and the validation ones used by fit_generator. 
For example, for the train data, why do you use a list ([x_batch, y_batch], [y_batch, x_batch]) instead of a tuple [x_batch, y_batch].

Thank you

**Comment by XifengGuo** [comment]
@Pelups 
Because the Model is a 2-input-2-output model. So we need to feed 4 tensors to the model.
