### ISSUE TITLE
Script causes a crash

### ISSUE THREAD

**Issue by jeankaye** [XifengGuo/CapsNet-Keras#52]
Running examples on Geforce 1080/linux crashes (restarts) the whole computer every time when training starts. While I do believe that power issues are one possibility strangely this is the only piece of code that so far is able to do it and the computer has trained many networks before without any issues.

I've tried to do some testing but it is really annoying since it means restarting everything all the time. Any ideas how to fix it, log the real reason for crashing or to rule out the power issues by slowing down the code somehow.

**Comment by XifengGuo** [comment]
@jeankaye 
I have no idea on the reason. I suggest you try to set `batch_size=10`.
