### ISSUE TITLE
ImportError: cannot import name 'combine_images'

### ISSUE THREAD

**Issue by fastesol** [XifengGuo/CapsNet-Keras#57]
Hi there,
while testing the script, I found that the utils module was not installed, So, I installed that through `pip install utils` (version = 0.9.0) after that, it couldn't import `combine_images` function. I have installed probably the wrong module. 

Can you please help me with this issue?

I'm using Python : 3.6.3
latest keras and tensorflow

Thank you!

**Comment by XifengGuo** [comment]
@fastesol 
I'm using the utils.py of my own. See CapsNet-Keras/utils.py
If there's a conflict, just change the name of utils.py to utils1.py or any other names you want.

**Comment by fastesol** [comment]
Oh!! That was the problem, Thank you very much for your help!
