### ISSUE TITLE
use another dataset

### ISSUE THREAD

**Issue by SoloyT** [XifengGuo/CapsNet-Keras#68]
Hi,
I want to use a 32x32x3 datasets for classification.
Based on capsule network, the primary capsule size is 8x8x32 8D vector right? Moreover, based on your code, I should modify input size of fully connected layers also. But I don't know how should I do?
Would you please help me in this issue?

Thanks!!

**Comment by XifengGuo** [comment]
@SoloyT Please try some examples of network definition and training on blogs. Then read the code in this repo carefully and you will find it is easy to reach your goal.
