### ISSUE TITLE
How to train on my dataset

### ISSUE THREAD

**Issue by shrybht** [XifengGuo/CapsNet-Keras#73]
Hi @XifengGuo ,

The given model is really good for MNIST dataset. I would like to train the model on PASCAL VOC/ MS COCO. Could you please let me know where and how do I the necessary changes to the code if that's possible?

**Comment by shrybht** [comment]
I too need help with the same.

**Comment by liuyang1273** [comment]
I've solved this problem, but how to add the number of digital capsules.Can you teach me?thank you @XifengGuo

**Comment by farhadmath** [comment]
I have a single GPU GTX1060. How can I run the capsnet on a single GPU instead of Multiple?

**Comment by shrybht** [comment]
@liuyang1273 Can you tell me how you had added the layer?

**Comment by shrybht** [comment]
@XifengGuo 
The problem that I am currently facing is that for MNIST, each image had a single number so for each input there is a single output. But in the case of MSCOCO, all images have multiple objects, so here for each input, we have multiple outputs. How to create the dataset in this case (i.e. the input vector x and the label vector y). I am currently trying to figure this out, if you get any ideas please let me know, any help would be appreciated.

**Comment by XifengGuo** [comment]
@shrybht Given two images containing three objects A, B, C. The first image contains A and B, the second B and C. Then we can set y=[[1,1,0],[0,1,1]]. I consider this a possible solution.
