### ISSUE TITLE
Possibility to ignore the reconstruction/decoder?

### ISSUE THREAD

**Issue by muaaz-khalid** [XifengGuo/CapsNet-Keras#81]
I think, reconstruction/decoder is not much helpful in learning the model, but creating an extra computation overhead. So, in order to prove this hypothesis/thought (or whatever you call it), is it possible to remove the decoder part?
This is what I tried so far.

    out_caps = Length(name='capsnet')(digitcaps)
    train_model = models.Model([x, y], out_caps)

but getting the following error

    ValueError: When passing a list as loss, it should have one entry per model outputs. The model has 1 outputs, but you passed loss=[<function margin_loss at 0x7f2f44f06ea0>, 'mse']

I'm sure, I'm doing it wrong way, probably have to reshape the out_caps to something else. Please help.

Thank you!

**Comment by JoyJulianGomes** [comment]
Hi @fastesol if you want to get rid of decoder/reconstruction, you should also exclude the loss function it is using which is 'mse'

**Comment by fastesol** [comment]
Thank you @joyjulianGomes can you  instruct the required changes in the code please? Sorry I’m new to this field.

**Comment by JoyJulianGomes** [comment]
@fastesol as you are new to this, working out the problem yourself would be better for the long run than just telling you what to change. I can give you some hints but you have to do it yourself.
1. you will not need the decoder part, use up to the layer 4.
2. checkout how keras Model works https://keras.io/models/model/ and change the inputs accordingly.

P.S.: I am new to this as well

**Comment by XifengGuo** [comment]
@muaaz-khalid You can just set the parameter `lam_recon=0` to prove your hypothesis.
