### ISSUE TITLE
TypeError: 'numpy.ndarray' object is not callable!

### ISSUE THREAD

**Issue by iphton** [XifengGuo/CapsNet-Keras#82]
I was trying to implement `CapsuleNet` for classifying the Native digits. All the images are RGB images and resize to **`32 X 32`** and dataset has **10** classification output.

> **X_train_all.shape**: `(72045, 32, 32, 3)`<br>
> **y_train_all.shape**: `(72045, 10)`

First, define the **CapsNet** model which takes the following parameters.

    # define model
    model = CapsNet(input_shape=[32, 32, 3],
                    n_class=10,
                    num_routing=3)

Ok, I think this chunk of information only enough here. However, then I define a function for data augmentation and both training the model. This function will iteratively train on the shuffling fold of the data set, defined below.

    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    cvscores = []
    Fold = 1
    for train, val in kfold.split(X_train_all, y_train_all):
        gc.collect()
        K.clear_session()
        print ('Fold: ', Fold)
        
        X_train = X_train_all[train]
        X_val = X_train_all[val]
        
        X_train = X_train.astype('float32')
        X_val = X_val.astype('float32')
        
        y_train = y_train_all[train]
        y_val = y_train_all[val]

        # train the model with data augmentation    
        train(model = model, data = ((X_train, y_train), (X_val, y_val)), epoch_size_frac = 0.5)
   
        
        # evaluate the model
        scores = model.evaluate(X_val, y_val, verbose = 0)
        print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))
        cvscores.append(scores[1] * 100)
               
        Fold = Fold + 1

The `train` function above, defined by you as follows:

```
def train(model, data, epoch_size_frac=1.0):
    """
    Training a CapsuleNet
    :param model: the CapsuleNet model
    :param data: a tuple containing training and testing data, like `((x_train, y_train), (x_test, y_test))`
    :param args: arguments
    :return: The trained model
    """
    # unpacking the data
    (x_train, y_train), (x_val, y_val) = data

    # callbacks
    log = callbacks.CSVLogger('CapsuleNet/log.csv')
    checkpoint = callbacks.ModelCheckpoint('CapsuleNet/CapsuleNet Weights Each Epochs/weights-{epoch:02d}.h5',
                                           save_best_only=True, save_weights_only=True, verbose=1)
    lr_decay = callbacks.LearningRateScheduler(schedule = lambda epoch: 0.001 * np.exp(-epoch / 10.))

    # compile the model
    model.compile(optimizer='adam',
                  loss=[margin_loss, 'mse'],
                  loss_weights=[1., 0.0005],
                  metrics={'out_caps': 'accuracy'})
    
    # Using the Tensorboard callback of Keras. 
    # https://stackoverflow.com/questions/42112260/how-do-i-use-the-tensorboard-callback-of-keras
    tbCallBack = keras.callbacks.TensorBoard(log_dir='CapsuleNet/CapGraph', histogram_freq=0, 
                                         write_graph=True, write_images=True)


    # -----------------------------------Begin: Training with data augmentation -----------------------------------#
    def train_generator(x, y, batch_size, shift_fraction=0.):
        train_datagen = ImageDataGenerator(width_shift_range = shift_fraction,
                                           height_shift_range = shift_fraction)  # shift up to 2 pixel for MNIST
        generator = train_datagen.flow(x, y, batch_size=batch_size)
        while 1:
            x_batch, y_batch = generator.next()
            yield ([x_batch, y_batch], [y_batch, x_batch])

    # Training with data augmentation. 
    model.fit_generator(generator=train_generator(x_train, y_train, 64, 0.1),
                        steps_per_epoch=int(epoch_size_frac*y_train.shape[0] / 64),
                        epochs = 1,
                        validation_data = [[x_val, y_val], [y_val, x_val]],
                        callbacks = [log, checkpoint, lr_decay, tbCallBack])
    # -----------------------------------End: Training with data augmentation -----------------------------------#


    return model
```

Now, when I start training, I get following error:

    TypeError                                 Traceback (most recent call last)
    <ipython-input-67-a8ca211d12a2> in <module>()
         19 
         20 
    ---> 21     train(model = model, data = ((X_train, y_train), (X_val, y_val)), epoch_size_frac = 0.5)
         22 
         23 
    
    TypeError: 'numpy.ndarray' object is not callable

I think I need to look over the dimension of the image. While I visualize the image I got the following:

    import matplotlib.pyplot as plt 
    print(X_train_all.shape)
    plt.imshow(X_train_all[1])

**(72045, 32, 32, 3)**

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/JGAO6.png

**Comment by XifengGuo** [comment]
@iphton You defined a variable `train` in `for train, val in kfold.split(X_train_all, y_train_all):` which has the same name with the function `train`. Just choose another name.
