### ISSUE TITLE
How to handle variable sized input? 

### ISSUE THREAD

**Issue by jeonghwaYoo** [XifengGuo/CapsNet-Keras#91]
I want to handle variable sized input using capsule network. 

In conventional CNN, it was able to cope with the input with the length changing through the fully convolutional layer.

In capsule network, how can I handle variable sized input?

I think the PrimaryCap is fine, but it can not cope with various lengths because of the fully connected part of the digit capsule layer.

`self.W = self.add_weight(shape=[self.num_capsule, self.input_num_capsule, self.dim_capsule, self.input_dim_capsule], initializer=self.kernel_initializer, name='W')`

we must know about `self.input_num_capsule` in this code.

How can I handle this problem? Do you have any idea?

**Comment by XifengGuo** [comment]
@jeonghwaYoo 
Similar to conventional CNN, before the fully connected layer, a GlobalMaxPooling can be applied. But regarding CapsNet, applying Pooling layers contradicts with the motivation of CapsNet.

**Comment by jeonghwaYoo** [comment]
@XifengGuo Okay, thank you so much!
